# Generated by Django 5.0.6 on 2024-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
