# Generated by Django 5.0.6 on 2024-07-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licensor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="is_verified",
            new_name="key_sent",
        ),
    ]
