# Generated by Django 5.0.6 on 2024-06-28 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0002_license_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
