# Generated by Django 5.0.6 on 2024-10-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensor', '0002_rename_is_verified_license_key_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
